### ISSUE TITLE
UX: Add 'Toast' Notification for Successful JSON Import

### ISSUE THREAD

**Issue by maretaayu** [insanistcontributor/suvarman#6]
Upon importing a JSON file to the Figma plugin, there is currently no notification or indication that the importing process has succeeded. As a user, it can lead to unnecessary confusion and possible repeated imports, because I'm not aware if the file has indeed been added.

Therefore, to enhance user experience and provide clear communication, it would be greatly helpful to include a 'toast' notification or a similar feedback system. This feature would notify users when a JSON file has been successfully imported, providing immediate awareness and confirmation of the action.

This proposed user feedback functionality would streamline the JSON-import process, making it more efficient, reducing repetition, and overall increasing usability for all Figma plugin users.
<img width="257" alt="image" src="https://github.com/insanistcontributor/suvarman/assets/36698449/c752cf20-0b79-40c4-828e-7f0858e684a4">

**Comment by ibedwi** [comment]
Thank you for submitting the issue!
Will work on this!
